/*
Creacion de BDD
*/

CREATE DATABASE ESTATAL;

/*
Creacion de tablas
*/

CREATE TABLE PRODUCTO (
ID_PRODUCTO INT PRIMARY KEY,
NOMBRE_PRODUCTO VARCHAR(25) NOT NULL
);

CREATE TABLE MOTIVO (
ID_MOTIVO INT PRIMARY KEY,
DESCRIPCION_MOTIVO VARCHAR(30) NOT NULL
);

CREATE TABLE TIPO_DEUDA(
ID_TIPO_DEUDA INT PRIMARY KEY,
DESCRIPCION_TIPO VARCHAR(15)
);

CREATE TABLE ACLARACION(
NRO_ACLARACION INT PRIMARY KEY AUTO_INCREMENT,
RUT_PERSONA VARCHAR(10) NOT NULL,
NOMBRE_PERSONA VARCHAR(100) NOT NULL,
BANCO VARCHAR(50) NOT NULL,
ID_PRODUCTO INT NOT NULL,
ID_MOTIVO INT NOT NULL,
ID_TIPO_DEUDA INT NOT NULL,
RAZON TINYTEXT NOT NULL,
FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO),
FOREIGN KEY (ID_MOTIVO) REFERENCES MOTIVO(ID_MOTIVO),
FOREIGN KEY (ID_TIPO_DEUDA) REFERENCES TIPO_DEUDA(ID_TIPO_DEUDA)
);
/*
Insercion de datos
*/

INSERT INTO PRODUCTO
VALUES
(1,"Tarjeta de crédito"),
(2, "Cuenta Corriente"),
(3, "Cuenta de ahorro"),
(4, "Tarjeta de debito");

INSERT INTO TIPO_DEUDA VALUES
(1,"Directa"),
(2,"Indirecta");

INSERT INTO MOTIVO VALUES
(1,"Sin deuda en el sistema"),
(2,"Sin deudas atrasadas"),
(3,"Debo menos de lo mostrado");

/*
Para sacar los datos del index de productos se les debe sumar uno antes de guardar, ya que el index en java comienza en 0 y el id en bdd comienza en 1
*/

